package com.example.frivolity.network.models.universalisapi

data class ApiItemDetail(
    val itemID: Int,
    val worldID: Int,
    val lastUploadTime: Long,
    val listings: List<Any>,
    val recentHistory: List<ApiItemSaleData>,
    val currentAveragePrice: Int,
    val currentAveragePriceNQ: Int,
    val currentAveragePriceHQ: Int,
    val regularSaleVelocity: Int,
    val nqSaleVelocity: Int,
    val hqSaleVelocity: Int,
    val averagePrice: Float,
    val averagePriceNQ: Float,
    val averagePriceHQ: Float,
    val minPrice: Int,
    val minPriceNQ: Int,
    val minPriceHQ: Int,
    val maxPrice: Int,
    val maxPriceNQ: Int,
    val maxPriceHQ: Int,
    val stackSizeHistogram: String,
    val stackSizeHistogramNQ: String,
    val stackSizeHistogramHQ: String,
    val worldName: String,
    val listingsCount: Int,
    val recentHistoryCount: Int,
    val unitsForSale: Int,
    val unitsSold: Int
)
